services:
  redis:
    image: redis:alpine
    container_name: redis_broker

  server1:
    build: .
    container_name: chat_server_1
    command: ["60005"]
    ports:
      - "60005:60005"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  server2:
    build: .
    container_name: chat_server_2
    command: ["60006"]
    ports:
      - "60006:60006"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis